export const chartConfigClass = {
    pageId:'',//页面id
    chartId:'',//图表id
    chartType:0,//图表类型
    x:0,//图表x坐标
    y:0,//图表y坐标
    width:0,//图表宽度
    height:0,//图表高度
    xData:'',//图表x轴列名
    yData:[],//图表y轴列名
    yFields:[],//图表y轴列名详细
    dataId:'',//图表配置数据源id
    dataUrl:'',//图表配置获取数据路径,
    backgroundColor:'transparent',//图表背景色
    borderRadius:0,//图表圆角
    borderWidth:0,//图表边框宽度
    borderStyle:'solid',//图表边框样式
    borderColor:'#fff',//图表边框颜色
}