export const DIALOG_ADD_PROJECT_VISIBLE = 'DIALOG_ADD_PROJECT_VISIBLE'
export const SET_TREE_DATA = 'SET_TREE_DATA'
export const DIALOG_ADD_PAGE_VISIBLE = 'DIALOG_ADD_PAGE_VISIBLE'
export const SET_PROJECT_NAME_LIST = 'SET_PROJECT_NAME_LIST'